DROP SEQUENCE usersIdSeq;
DROP SEQUENCE addressIdSeq;
DROP SEQUENCE electionsIdSeq;
DROP SEQUENCE partiesIdSeq;
DROP SEQUENCE candidatesIdSeq;

DROP SEQUENCE presidentialCandidatesIdSeq;
DROP SEQUENCE parliamentaryCandidatesIdSeq;
DROP SEQUENCE senateCandidatesIdSeq;
DROP SEQUENCE referendumQuestionsIdSeq;

DROP SEQUENCE presidentialVotesIdSeq;
DROP SEQUENCE parliamentaryVotesIdSeq;
DROP SEQUENCE senateVotesIdSeq;
DROP SEQUENCE referendumVotesIdSeq;

------------------------

CREATE SEQUENCE usersIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE addressIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE electionsIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE partiesIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE candidatesIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE presidentialCandidatesIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE parliamentaryCandidatesIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE senateCandidatesIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE referendumQuestionsIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE presidentialVotesIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE parliamentaryVotesIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE senateVotesIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE referendumVotesIdSeq	MINVALUE 1 START WITH 1 INCREMENT BY 1;